### ISSUE TITLE
Can the apk file being installed on any android device?

### ISSUE THREAD

**Issue by kifgep** [Veyron2K/Carlinkit-CPC200-Autokit-Reverse-Engineering#1]
Can I install the apk on my mobile phone, then use a otg adapter connect to my iPhone?

Will this work or the apk is for specific device only?

**Comment by Veyron2K** [comment]
Yes, you can install apk on your android device and use box with otg adapter, but its will work only if your android device have USB-C port. Micro-USB not give enough power to start the Carlinkit box.
